version: "3.8"

services:

  frontend:
    image: paulhjwu/ict381_staycation:v.0.1
    ports:
      - "5000:5000"
    networks:
      - ict381network
  db:
    image: paulhjwu/ict381_mongo:v.0.1
    ports:
      - "27017:27017"
    networks:
      - ict381network
  nginx:
    image: paulhjwu/ict381_nginx:v.0.1
    ports:
      - "80:80"
    networks:
      - ict381network
    depends_on:
      - frontend

networks:
  ict381network:

